openapi: 3.0.0
info:
  title: Review API1_PROG3
  version: 1.0.0
servers:
  - url: https://prog3API_server.com
    description: Mock server for testing
paths:
  /books:
    get:
      summary: Get a list of books
      parameters:
        - name: nameofbook
          in: query
          description: Filter books by idname
          schema:
            type: string
        - name: startofDate
          in: query
          description: Start date of interval date
          schema:
            type: string
            format: date
        - name: endofDate
          in: query
          description: End date of interval date
          schema:
            type: string
            format: date
      responses:
        '100':
          description: Get Successfuly of the list of books
    post:
      summary: Add new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '101':
          description: Book created
    put:
      summary: Update book information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: updated update successfully
    delete:
      summary: Delete a book by ID
      responses:
        '200':
          description: Book deleted successfully

  /authors:
    get:
      summary: Get a list of authors
      parameters:
        - name: authorName
          in: query
          description: Filter authors by name
          schema:
            type: string
      responses:
        '200':
          description: Successfuly got a list of authors
    post:
      summary: Add new author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '201':
          description: Author added successfuly
    put:
      summary: Update author information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '200':
          description: Author updated successfully
    delete:
      summary: Delete an author by ID
      responses:
        '200':
          description: Author deleted successfully

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        bookName:
          type: string
        author:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum: [DRAMA,ORROR, OTHER]
        releaseDate:
          type: string
          format: date
    Author:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        sex:
          type: string
          enum: [F, M]